### ISSUE TITLE
error when pushing some metrics

### ISSUE THREAD

**Issue by monnierant** [prometheus/pushgateway#100]
Hi

I'm trying to push some metrics from a linux to another (to federate some datas of multiple prometheus server all over the world to one prometheus main server in the cloud).

I know it's not a good idea and I have read all the suggestion but I must do it this way accordingly to my security requirements.

As now the context I down here is some exemple of the issue I got.

Firstly I curl a metrics file from the local prometheus server into a metrics.txt file. 
And then I push them to the push gateway (with PUT argument)
```
curl -g 'http://127.0.0.1:9090/federate?match[]={job="prometheus"}' -o metrics.txt
cat metrics.txt | curl -X PUT --data-binary @- http://testpushgatewayip:9091/metrics/job/test/instance/valpuppet01
```

With this I got a lot of issue (one by one) on some specific metrics. (Seems to be then with big value)

So I have edit the metrics.txt file to test part by part my metrics file. A lot of metrics works fine.

I got a lot of this kind of issue from prometheus metrics (more than 30 for the moment)

So i was wondering is there an issue in the pushgateway code or is there a settings to just ignore validation and get all the metrics easily ?

Here are some exemple of bad metrics
Metrics:
```
# TYPE go_memstats_alloc_bytes untyped
go_memstats_alloc_bytes{group="cadvisor",nickname="localcache",job="prometheus",instance="cadvisor:8080",monitor="docker01"} 1.3971984e+07 1482227918852
go_memstats_alloc_bytes{job="prometheus",instance="localhost:9090",group="prometheus",nickname="prometheus",monitor="docker01"} 1.92002016e+08 1482227913696
```
Error:
```
An error has occurred:

expected gauge in metric go_memstats_alloc_bytes label:<name:"group" value:"cadvisor" > label:<name:"instance" value:"valpuppet01" > label:<name:"job" value:"test" > label:<name:"monitor" value:"docker01" > label:<name:"nickname" value:"localcache" > untyped:<value:1.3971984e+07 > timestamp_ms:1482227918852 
```

Metrics:
```
# TYPE go_gc_duration_seconds untyped
go_gc_duration_seconds{quantile="0.5",nickname="localcache",job="prometheus",instance="cadvisor:8080",group="cadvisor",monitor="docker01"} 0.000990441 1482227918852
go_gc_duration_seconds{job="prometheus",instance="cadvisor:8080",group="cadvisor",nickname="localcache",quantile="0.75",monitor="docker01"} 0.0027681560000000003 1482227918852
go_gc_duration_seconds{quantile="0.25",job="prometheus",instance="cadvisor:8080",group="cadvisor",nickname="localcache",monitor="docker01"} 0.000717085 1482227918852
go_gc_duration_seconds{instance="cadvisor:8080",quantile="0",group="cadvisor",nickname="localcache",job="prometheus",monitor="docker01"} 0.000361441 1482227918852
go_gc_duration_seconds{nickname="prometheus",job="prometheus",instance="localhost:9090",group="prometheus",quantile="0.5",monitor="docker01"} 0.0019649850000000003 1482227913696
go_gc_duration_seconds{quantile="0",nickname="prometheus",job="prometheus",instance="localhost:9090",group="prometheus",monitor="docker01"} 0.000223264 1482227913696
go_gc_duration_seconds{group="prometheus",quantile="0.25",nickname="prometheus",job="prometheus",instance="localhost:9090",monitor="docker01"} 0.0005924060000000001 1482227913696
go_gc_duration_seconds{nickname="localcache",job="prometheus",instance="cadvisor:8080",group="cadvisor",quantile="1",monitor="docker01"} 0.01865201 1482227918852
go_gc_duration_seconds{instance="localhost:9090",group="prometheus",quantile="0.75",nickname="prometheus",job="prometheus",monitor="docker01"} 0.0044686840000000005 1482227913696
go_gc_duration_seconds{quantile="1",group="prometheus",nickname="prometheus",job="prometheus",instance="localhost:9090",monitor="docker01"} 0.045553997000000006 1482227913696
```

Error:
```
An error has occurred:

expected summary in metric go_gc_duration_seconds label:<name:"group" value:"cadvisor" > label:<name:"instance" value:"valpuppet01" > label:<name:"job" value:"test" > label:<name:"monitor" value:"docker01" > label:<name:"nickname" value:"localcache" > label:<name:"quantile" value:"0" > untyped:<value:0.000361441 > timestamp_ms:1482227918852 
```

**Comment by beorn7** [comment]
The problem here is a combination of multiple known issues, and they get combined here because you are implementing a multitude of anti-patterns.

Because the Prometheus server doesn't store the metadata (type, help string) of samples yet, all metrics fetched via federation are `untyped`. In your case, you are fetching _all_ metrics via federation (anti-pattern), including those automatically exposed by any process (`process_…`) or by any Go process `go_…`). You push all those metrics to the Pushgateway (anti-pattern), which also has `process_…` and `go_…` metrics of its own. The latter are still typed, but the former aren't. That's a collision detected by the Pushgateway. The Prometheus exposition format simply doesn't allow to export the same metric with two different types (`untyped` vs. `gauge` or `untyed` vs. `summary` above).

Both federation and pushing to the Pushgateway is meant to happen on selected few metrics. While you could attempt some makeshift solutions in your case to work around the immediate issues you are running into (filter out offending metrics, or set their type in some postprocessing of the text file), it will make your setup even more brittle. You are fighting a twice uphill battle here.

**Comment by monnierant** [comment]
Hi

Thanks a lot for your explanation.

For info here is how I swap around this situation.

I just add a prefix before each metrics name so there is no collision between them.

Of course I understand how weird it is.

Thanks a lot for your help I close the issue.
