### ISSUE TITLE
different dimensions in same metric will overwrite each other

### ISSUE THREAD

**Issue by yupeng820921** [prometheus/pushgateway#107]
I write a bash script, put 3 data points to the pushgateway, they are in the same metric (my_request1_ms_sum), but have different dimensions (the key1 are difference):

echo 'my_request1_ms_sum{key1="aa",key2="11"} 10.0' | curl -i -H "Content-Type: text/plain\r\n" -X PUT --data-binary @- http://localhost:9091/metrics/job/test_job
echo 'my_request1_ms_sum{key1="bb",key2="11"} 10.0' | curl -i -H "Content-Type: text/plain\r\n" -X PUT --data-binary @- http://localhost:9091/metrics/job/test_job
echo 'my_request1_ms_sum{key1="cc",key2="11"} 10.0' | curl -i -H "Content-Type: text/plain\r\n" -X PUT --data-binary @- http://localhost:9091/metrics/job/test_job

I run the bash script for every 20 seconds, from prometheus, I can only get the data with dimension key1="cc", can not get the data with dimension key1="aa" or key1="bb". Here is my pushgateway version:
pushgateway-0.3.1.linux-amd64

Is it a bug or I misunderstand anything?

**Comment by beorn7** [comment]
You misunderstood something, see https://github.com/prometheus/pushgateway#put-method : "All metrics with the grouping key specified in the URL are replaced by the metrics pushed with PUT."

You have to PUT all three metrics in the same HTTP request.

In general, it makes more sense to ask questions like this on the [prometheus-users mailinglist](https://groups.google.com/forum/#!forum/prometheus-users") rather than in a GitHub issue.
