### ISSUE TITLE
Don't accept timestamps from pushes

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/pushgateway#109]
My ruminations on https://docs.google.com/document/d/1ordTPfUSaGvaBolUGeLChATwgc1xUhUxfUhudYoOeMw/edit indicate that my original plan of having the pushgateway ultimately expose data with the timestamp it was pushed at is unworkable.

Given this, it appears there are no valid use cases for timestamps with the pushgateway. Accordingly I propose we either silently drop or hard reject pushes containing timestamps, as everyone we've seen doing this so far was using the pgw in an improper fashion.

Once this is done, I think it'd be safe to client libraries to support timestamps for the handful of advanced users who need them. Up to now, (almost) everyone asking for timestamps in client libraries was trying to incorrectly use them with the pushgateway - so if we make that impossible then the abuse risk is as mitigated as it's going to get.

**Comment by tckb** [comment]
@brian-brazil  whats the current status of supporting timestamps? I tried ingesting the back dated samples. the gateway accepted it but prometheus isn't showing any data.

**Comment by brian-brazil** [comment]
Please take user-support queries to https://groups.google.com/forum/#!forum/prometheus-users

**Comment by ethanocentricity** [comment]
This would be quite a bad change for some of our use cases.  Admittedly, we're trying to do some advanced things with prometheus.

We use prometheus (with ingestion through the push gateway) for two purposes: 

1. keeping a historical record for charting in grafana
2. alerting using the alert manager.

For 2, we use the scrape time due to the issues discussed elsewhere ("what is the latest time for a time series").  
But for 1, we use a more business meaningful timestamp due to the use case described below.

To work around the fact that there is one timestamp associated with the time series query, we actually ingest two timeseries through the push gateway (using different names like "metric" and "metric_by_scrapetime").  
We can then use "metric" in grafana for meaningful charting, and "metric_by_scrapetime" with the alertmanager for alerting based on the latest value ingested.

This is obviously hacky, but works around the limitations quite well without compromising functionality or business requirements. 

Rather than eliminate explicit timestamp support, I'd rather have prometheus provide an option to have multiple versions of the meric timeseries (one using the explicit business meaningful timestamp for charting and one using the scrape timestamp for use with alerting.)

Our Use Cases:  

1. We have processes that calculate metrics from events. Since events can be late arriving, we need to wait for a window period to expire before we finalize those metrics.  At that point, we export them to prometheus (by pushing to the gateway and setting the timestamp explicitly to the window period timestamp).  The scrapetime therefor trails the metric time by the window period.
2. We have processes that predict future values.  We push those using a timestamp in the future (so the scrapetime precedes the business meaningful time for charting).

**Comment by brian-brazil** [comment]
This sounds like the sort of inappropriate usage of the pushgateway I'm trying to discourage, please see https://prometheus.io/docs/practices/pushing/

Prometheus is a metrics system, not an event logging system.

**Comment by ethanocentricity** [comment]
Thanks for the quick response.  
Perhaps you can explain to me what you consider an event as opposed to a metric.
Because the use case I described is exactly capturing metrics in prometheus. It just so happens that the metrics don't have a timestamp of "now".

In the use case I described above, systems upstream from prometheus (and upstream from the push gateway) do the event processing, aggregating those events into metrics over a time period (usually a minute, but perhaps longer or shorter based on the use case), and then pushes those metrics to prometheus when the proper windowing time period for late arriving events has passed.
To me, that sounds like using prometheus as a metrics system, not event logging.
We use other systems for event logging and analysis (ELK, big data, etc). 

Thanks again.

**Comment by brian-brazil** [comment]
> In the use case I described above, systems upstream from prometheus (and upstream from the push gateway) do the event processing, aggregating those events into metrics over a time period (usually a minute, but perhaps longer or shorter based on the use case)

The Prometheus answer to this is to directly instrument your upstream applications, and have Prometheus scrape them.

The pushgateway is not a way to make Prometheus into a push-based system. The pushgateway is for service level batch jobs.

**Comment by miguelHx** [comment]
@brian-brazil let's assume for instance that there is a prometheus server that scrapes a pushgateway every 60 seconds.  Now, the pushgateway is taking in metrics from instrumented application code.  Let's assume that the metric we are tracking is error count (COUNTER) for a service-level batch job that runs temporarily.  In the interval, at 1s, the batch job runs and increments the counter, 1 error so far.  At 10s, the job gets triggered and runs again, yielding another error, that's 2.  However, no more errors for the remaining 50 seconds.  When Prometheus scrapes the pushgateway, will it use a timestamp at 10s (the most recent counter update), or will it timestamp at 60s when it scrapes?

**Comment by miguelHx** [comment]
@beorn7 thank you for the resource.

**Comment by xianyuLuo** [comment]
I also want to customize the timestamp
