### ISSUE TITLE
Pushgatewag will igore some metric when they have the same job name

### ISSUE THREAD

**Issue by zfl926** [prometheus/pushgateway#114]
Hi all, 

Our project is using pushgate to collect some metric from our webapps and the metrics is like below:
java_heap_size{app="pop-job-server",instance="",ip="172.16.123.224",job="push-pop-java-infos"}  xxxx
java_heap_size{app="pop-rest-server",instance="",ip="172.16.123.224",job="push-pop-java-infos"} yyyy

but pushgateway always igores one  metric and when I change the metric like:
java_heap_size{app="pop-job-server",instance="",ip="172.16.123.224",job="push-pop-java-infos-job"}  xxxx
java_heap_size{app="pop-rest-server",instance="",ip="172.16.123.224",job="push-pop-java-infos"} yyy

I just change one metrics's job name to [push-pop-java-infos-job] and the missing message is back again. So can some one me is this a bug or is it OK ?

**Comment by beorn7** [comment]
This is most likely not a bug.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users") rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
