### ISSUE TITLE
No instance value of pushgateway's metrics

### ISSUE THREAD

**Issue by krisoul** [prometheus/pushgateway#130]
The metrics of pushgateway's :
```
agent_up{hostname="test",instance="",job="ops-machines",version="5.2.9.5"} 1
agent_up{hostname="test",instance="",job="ops-machines",version="5.2.9.5"} 1
```

my code in the push host:
```
push.AddFromGatherer("ops-machines", nil, "ip:port", somePromRegistry)
```

but pushgateway said:
![tim 20170823183739](https://user-images.githubusercontent.com/3422759/29611954-3814f0c4-8832-11e7-8669-4ac2dfaf47ea.png)

so why my instance value is empty?

**Comment by krisoul** [comment]
second question:
you see in the first picture, two same metrics?

**Comment by beorn7** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by krisoul** [comment]
@beorn7 so could you help me with this question?
