### ISSUE TITLE
Not pushing metrics for labels remove them from metrics result - as intended?

### ISSUE THREAD

**Issue by DonMartin76** [prometheus/pushgateway#133]
Hi there,

I just ran into an issue I didn't expect when using the Pushgateway to push results for a set of monitoring tests from the outside into the cluster. The issue I have is the following:

We run a set of end-to-end monitoring tests as a batch job outside of a Kubernetes cluster, and then subsequently push the results (durations, last success time stamp, last run time stamp), using the following metric names:

* `monitor_last_run{case="<case name>"}`
* `monitor_last_success{case="<case name>"}`
* `monitor_duration{case="<case name>"}`

We only push `monitor_last_success` for a specific case if it actually succeeded, and that now triggers the following problem: A query for `time() - monitor_last_success{case="<some case>"}` for a case which fails renders an empty result, as the pushgateway does not expose that metric with that specific label anymore. Probably because there was an update of `monitor_last_success` (some cases were successful, some weren't), and labels which weren't part of that update aren't exposed anymore.

We could probably come up with a couple of different workarounds for this, but nonetheless I wanted to ask whether this is intended behavior, or should/could I try to "fix" this in the pushgateway?

Best regards,
Martin

**Comment by beorn7** [comment]
This is the intended behavior.

Discussing the correct usage of the Pushgateway for this case makes more sense to happen on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by DonMartin76** [comment]
Okidoki. Thanks for clarifying. Back to the planning board then.
