### ISSUE TITLE
How to push the same metrics name but have different key-value pair ?

### ISSUE THREAD

**Issue by haley05** [prometheus/pushgateway#134]
Dear, 
I have some question to ask, I'm looking forward to your reply.
There are two nodes(NodeA, NodeB) Push same metrics but different key-value pairs to one pushgateway. 
Step:
1. NodeA push metrics at time t1
2. NodeB push metrics at time t2(t2 > t1). 
3. Then Prometheus scrape them after t2
Result:
The metrics pushed by NodeA replaced by NodeB.
Question: How can I keep both of them for prometheus? 

Best regards.

**Comment by beorn7** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
