### ISSUE TITLE
Clash between pushgateway's own metrics and pushed metrics

### ISSUE THREAD

**Issue by jeffhiltz** [prometheus/pushgateway#138]
Hi, we're trying to send metrics from a Node.js process to a Pushgateway using the Node.js prom-client.  We're running into what seems to be the same problem as seen in https://github.com/prometheus/pushgateway/issues/27.  There are existing metrics for the Pushgateway (eg: `process_start_time_seconds`) that have no labels but our process is trying to push a metric with the same name that does have labels.  Despite looking into the previous issue and digging around we can't figure out how to resolve this.  Is there some way to attach labels to the metric's that belong to the Pushgateway itself?

pushgateway v0.3.1
node.js prom-client v10.1.1

(Also, it seems odd that the POST to the Pushgateway is succesful with a response code of 202, but then any GETs to the /metrics path return a 500 ("...has label dimensions inconsistent with previously collected metrics in the same metric family".)  I'm surprised that the invalid metrics are accepted and then able to disable the Pushgateway.  Maybe this should be a separate issue, or maybe I'm just doing it wrong...)

Anyway, any help you could offer would be appreciated.

**Comment by beorn7** [comment]
The relevant comment on #27 is https://github.com/prometheus/pushgateway/issues/27#issuecomment-75984276 . As @brian-brazil said, we need to solve fundamentally how to deal with labels that are effectively target labels on metrics pushed to the Pushgateway. In the current state, pushing the metrics as you tried fails by design. (In other words: It would be a bug if it succeeded.) My current feeling is we could allow an optional separate `/metrics` endpoint on the Pushgateway (e.g. `/pushed_metrics`) only to be used for those that need it. But that has implication and needs to be thought through carefully.

About the proposed immediate reject: That's also by design, see https://github.com/prometheus/pushgateway#put-method . The current design aims to make the push as fast as possible and only does the processing later. An immediate check would make pushing the slower the more metrics are currently saved on the Pushgateway.

**Comment by brian-brazil** [comment]
I think a key question here is why are you not scraping the Node.js client directly? Metrics like process_start_time_seconds should not be ending up in the pushgateway.

**Comment by jeffhiltz** [comment]
Hi guys.  Thanks for the quick response.  The reason we're using the Pushgateway now (as far as I know) is as a medium term solution until we're ready to do the service discovery etc. required to do the scraping.  Our DevOps team has started using Prometheus at the system level and we're experimenting with using it for our application metrics.

As for those "default" metrics not being relevant to users of the Pushgateway I'm a little surprised.  As it happens the Node.js code in question is indeed a long-running server, but it could just as easily be a cronjob which is what the Pushgateway is intended for.  In the case of periodic script I would still like to collect metrics such as `process_cpu_seconds_total` and `process_resident_memory_bytes` (which are also colliding with unlabeled metrics in the Pushgateway.)

Anyway, I had the understanding from https://github.com/prometheus/pushgateway/issues/27#issuecomment-81694934 that there was a fix/workaround but I just didn't understand what it was.  It seems now though that what I'm seeing is in fact the expected behaviour.

**Comment by brian-brazil** [comment]
I'd suggest a read of https://prometheus.io/docs/practices/pushing/

**Comment by jeffhiltz** [comment]
Yeah, I guess we'll have to wait until we're ready to try scraping.  Thanks.
