### ISSUE TITLE
Bad pushes poison future /metrics calls, causing 500s

### ISSUE THREAD

**Issue by aecolley** [prometheus/pushgateway#141]
I pushed some improperly formatted metrics to a pushgateway, and then pushgateway started serving 500s to prometheus.

What I POSTed (the error was the missing keyword `TYPE`):
```
# last_success_timestamp gauge
# HELP last_success_timestamp POSIX time when this job last completed successfully
last_success_timestamp 1513267492.667234008
```

A subsequent GET:
```
HTTP/1.1 500 Internal Server Error
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Thu, 14 Dec 2017 16:06:27 GMT
Content-Length: 215

An error has occurred:

expected gauge in metric last_success_timestamp label:<name:"instance" value:"stop backup-dc loadtest - bro" > label:<name:"job" value:"jenkins_job" > untyped:<value:1.513267492667234e+09 >
```

What I expected: the POST should get the error, and the posted metrics should not be accepted. Alternatively, if it's a firm design decision to accept dodgy metrics, then don't check them when serving GET /metrics. To put it another way, [be liberal in what you accept and conservative in what you transmit](http://www.catb.org/jargon/html/P/Postels-Prescription.html).

Why this is worth a bug fix: the monitoring system should be able to continue functioning when one of the production services it monitors is misbehaving. The pushgateway was unavailable until properly-formatted metrics were pushed to replace the bad ones.

**Comment by beorn7** [comment]
This is another incarnation of #94 .

The problem here is even a bit more subtle: What you POST'd is syntactically correct. Your first line is just a normal comment, and the metric is assumed to be of type `untyped` (for lack of a `TYPE` line). The error only manifests itself upon server the totality of metrics because then we have some `last_success_timestamp` metrics that are gauges, and some that are untyped, which is inconsistent in the Prometheus data model.

As graceful degradation, we could leave out inconsistent metrics, but we should then also have a metric that tells us about the inconsistency so that we can alert on it. The current behavior is in a way a safe conservative approach: Better serve a 500 than silently serving something incomplete.

Since this is really the same discussion as #94, I'll close this one as a dupe so that any further discussion can happen there.
