### ISSUE TITLE
Push multiple metrics within a request

### ISSUE THREAD

**Issue by zebozhuang** [prometheus/pushgateway#156]
I'm using golang to push metrics to pushgateway, but I can not figure out any solutions to push multiple metrics within a request according to the API documents though the command line supports it.

**Comment by beorn7** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
