### ISSUE TITLE
make: cannot find package

### ISSUE THREAD

**Issue by ezyang** [prometheus/pushgateway#165]
```
ezyang@autobox:~/Dev/pushgateway$ make
>> formatting code
can't load package: package _/home/ezyang/Dev/pushgateway: cannot find package "_/home/ezyang/Dev/pushgateway" in any of:
	/usr/lib/go-1.6/src/_/home/ezyang/Dev/pushgateway (from $GOROOT)
	($GOPATH not set)
can't load package: package _/home/ezyang/Dev/pushgateway/handler: cannot find package "_/home/ezyang/Dev/pushgateway/handler" in any of:
	/usr/lib/go-1.6/src/_/home/ezyang/Dev/pushgateway/handler (from $GOROOT)
	($GOPATH not set)
can't load package: package _/home/ezyang/Dev/pushgateway/storage: cannot find package "_/home/ezyang/Dev/pushgateway/storage" in any of:
	/usr/lib/go-1.6/src/_/home/ezyang/Dev/pushgateway/storage (from $GOROOT)
	($GOPATH not set)
Makefile:40: recipe for target 'format' failed
make: *** [format] Error 1
```

**Comment by beorn7** [comment]
There is a problem with your Go setup. Also, 1.6 is a rather old version of Go. I would expect that you need at least 1.7 to compile the Pushgateway. In general, I'd recommend to use a binary release from https://github.com/prometheus/pushgateway/releases (unless you need newer features - also, v0.5 is overdue, but it will happen in June).

Even more generally, it makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by ezyang** [comment]
In the end, I solved it by sticking the pushgateway checkout in the "conventional" location in GOPATH. It would be nice if the README mentioned this; when I see "run `make` to build" I assume I'm looking at a project that follows the make conventions (which means that it doesn't matter where you put the source dir.)

**Comment by beorn7** [comment]
Go has very strict conventions where to put the source dir. I'm not aware that `make` would have similarly strict conventions overriding the conventions of the language `make` is used for.
But anyway, the build system is, in fact, shared between all larger repos in the Prometheus org. If you think this should be rectified or documented, I still recommend to open a discussion on the mailing list.
(Perhaps the [prometheus-developers mailing list](https://groups.google.com/forum/#!forum/prometheus-developers) is even a bit more appropriate in this case.)
