### ISSUE TITLE
Expose metrics metadata in HTTP API

### ISSUE THREAD

**Issue by pbadenski** [prometheus/pushgateway#184]
The way I understand it when interacting with a registered metric via pushgateway API (PUT, POST, DELET, etc.) you need to match grouping key exactly. I also believe that the only way to figure out the grouping key for metric is from pushgateway UI (https://github.com/prometheus/pushgateway/blob/master/handler/status.go#L85 seems to be doing it). This becomes especially relevant when trying to remove metrics from pushgateway. 

Building on top of that - it would be very helpful to have this information available through HTTP API in a machine readable format (JSON?). Ideally combined with other information being reported in the UI.

**Comment by snebel29** [comment]
The above link to `status.go#L85` seems to be not relevant anymore since is pointing to master which changed over time, I think it's fair to assume that the below line was probably the referred one

https://github.com/prometheus/pushgateway/blob/231071b3e0a57b58df717bba5f4e5d88cac95389/handler/status.go#L85

My understanding is that what we want to do here is

1. Provide a programmatic way of retrieving metric information, including its grouping key. Something like allow `GET /metrics` and returning results back, may be in pages of N metrics => To verify if Prometheus is doing something similar, to match its behavior.
2. Adapt the UI to use the new GET endpoint instead of relying on templating them.

Those could come in separate PRs, am I right?

If there is no opposition I'm happy to take this issue.

Cheers

**Comment by beorn7** [comment]
Yes, that's broadly correct. `/metrics` is probably not a good endpoint as it is used for the exposition of (all the) metrics in the Prometheus exchange format. It should be an endpoint like `/api/v1/...` (where the `...` can certainly be `metrics` – best to see what the Prometheus server is doing there). Pagination would be great, but it doesn't have to be in the initial solution (we don't have pagination in the status page right now, and pushing an excessive amount of metrics to the PGW has a smell anyway).

**Comment by snebel29** [comment]
Great, will work on this next week.

**Comment by snebel29** [comment]
Hi @beorn7,

I took a brief look to the [Prometheus querying API](https://prometheus.io/docs/prometheus/latest/querying/api/) and found:

- API Endpoints are all exposed on `/api/vN/` path.
- Returns JSON using the [following](https://prometheus.io/docs/prometheus/latest/querying/api/#format-overview) format/structure.
- There is multiple endpoints to get metrics data and time series, using different filters and matching patterns (query, range, series, etc.).
- The closest endpoint is possibly "series", but since Pushgateway is technically not holding metric time series but groups of metrics with only the last value instead, semantically speaking "metrics" feels more appropriate.

In a side note looking to the Pushgateway API, I think it's confusing to have PUT, POST and DELETE methods for metric groups under `/metrics` and then GET method (the new one to get metric groups) under `/api/v1/metrics`, as you mentioned Prometheus format is ubiquitously exposed on `/metrics`, I feel that for consistency all of the group metrics endpoints should exist under `/api/v1/metrics`, my guess is that this is just for legacy reasons and a painful breaking change to implement, am I right? is there anything else?.

What I have in mind is adding `/api/v1/metrics` endpoint that answers to GET verb only, for simplicity I was thinking not to provide any filtering yet. example: by label.

I hand crafted a few examples, assuming the current grouping key still using `uint64` hashed values instead of the one coming using sorted label strings.

- A successful request to the new endpoint would return metric groups in the data field:
```
{
  "status": "success",
  "data": [
    {
      "grouping_key": "7344000326925601179",
      "labels": {"job": "some_job", "label1": "label1_value"},
      "metrics": {
        "some_metric_1": {
          "type": "untyped",
          "help": "",
          "value": "3.14",
          "labels": {"instance": "", "job": "some_job", "label1": "label1_value"}
        },
        "push_failure_time_seconds": {
          "type": "gauge",
          "help": "Last Unix time when changing this group in the Pushgateway failed.",
          "value": "0",
          "labels": {"instance": "", "job": "some_job", "label1": "label1_value"}
        },
        "push_time_seconds": {
          "type": "gauge",
          "help": "Last Unix time when changing this group in the Pushgateway succeeded.",
          "value": "1570631285.6778247",
          "labels": {"instance": "", "job": "some_job", "label1": "label1_value"}
        }
      }
    }
  ]
}
```

- A failed request to the new endpoint would look like this
```
{
  "status": "error",
  "errorType": "unknown_error",
  "error": "unknown error"
}
```

How does this look like initially?

Cheers

**Comment by beorn7** [comment]
I think `/api/v1/metrics` as the endpoint to retrieve the pushed metrics data as JSON via a GET request is fine.

Note that a GET on `/metrics` retrieves _all_ the metrics in Prometheus exposition format (rather than JSON).

One could make the argument that pushing should happen via the `/api/v1/metrics` endpoint, once it exists. However, note that the `/api/v1/...` endpoints of the Prometheus server all speak JSON. So the counter-argument would be that `/metrics` is for Prometheus exposition format, while `/api/v1/metrics` is for JSON.

No filtering ar paging should be fine for the first iteration. (Even once we have released v1 of the PGW, we can mark the JSON API as experimental so that we don't have to bump versions all the time while we are still experimenting.)

The mock-up for the JSON output looks fine, with the exception that I would probably not return the grouping_key at all. The new grouping_key is (deliberately) not a valid UTF-8 string, so you needed a special encoding for it. However, I see the grouping_key as internal anyway. (If Go allowed maps as keys for other maps, we wouldn't even need it.) The current web UI doesn't expose the grouping_key anywhere. From an external perspective, it should just not exist. The grouping is defined solely by the  grouping labels (which perhaps you should call `grouping_labels` in your output rather than just `labels`).

**Comment by snebel29** [comment]
Yeah, all makes sense to me.

**Comment by drumilpatel2000** [comment]
@beorn7 What is the status of adding UI?Mentioned in this [Comment]( https://github.com/prometheus/pushgateway/issues/184#issuecomment-393186670). Can I work on adding UI if it is in the roadmap of pushgateway?

**Comment by beorn7** [comment]
Nobody is working on a revamp of the PGW UI, as far as I am aware of.

I don't know if anybody plans to work on an API as described in the issue.

I'd say a new UI should closely follow the pattern we use for the new UI of prometheus/prometheus (see [related issues](https://github.com/prometheus/prometheus/issues?utf8=%E2%9C%93&q=label%3Acomponent%2Freact-ui+) for details). But to make it work, we need an API that can drive such a UI first. I'd suggest to talk to @snebel29 if he still plans to work on the API part.

**Comment by drumilpatel2000** [comment]
If @snebel29  is not available can I work on this issue? @beorn7

**Comment by beorn7** [comment]
Certainly. Thank you very much.

**Comment by drumilpatel2000** [comment]
@beorn7 Does it not make sense to use `router` From `common/router` Than using directly `httprouter` From `github.com/julienschmidt/httprouter`?

**Comment by beorn7** [comment]
All the HTTP routing stuff has confused me and others in the past. I vaguely remember that we wanted to migrate to common/router, but there were unexpected complications, so we kept the current approach but made sure that the `--web.route-prefix` and `--web.external-url` worked the same as for the Prometheus server.

If you are now adding a proper HTTP API, it might make sense to try again to migrate. You have to play around and see how it goes.

**Comment by beorn7** [comment]
Reopening, because we still need a test for the API. @drumilpatel2000 gentle reminder for you.

**Comment by drumilpatel2000** [comment]
> Reopening, because we still need a test for the API. @drumilpatel2000 gentle reminder for you.

Quite busy this weekend will start work from monday :smile:
