### ISSUE TITLE
Regression: Custom grouping labels are broken

### ISSUE THREAD

**Issue by grobie** [prometheus/pushgateway#185]
The combination of registering a common `push_time_seconds` metric for every metrics group and the strict metrics validation of client_golang break the feature of the providing custom grouping labels as documented (`/metrics/job/<JOBNAME>{/<LABEL_NAME>/<LABEL_VALUE>}`). At the moment only `JOB` and optionally `INSTANCE` labels can be used.

**Comment by beorn7** [comment]
This is pretty harsh… I have to think for a moment how we can manoeuvre ourselves out of this rabbit hole…

**Comment by grobie** [comment]
We've lost another pushgateway over the weekend.

Here are the options I see:

1. Keep `push_time_seconds`
  a. Remove/disable the consistency check
  b. Get the consistency check to pass (by adding the missing labels to all series)
2. prefix `push_time_seconds` with the job name
  a. Always
  b. Only if a metric group uses custom grouping labels
3. Drop `push_time_seconds` completely
4. Remove the concept of grouping labels, only group by job, attach labels directly

Am I missing anything?

My opinion:
- 1b. feels really lame, either there is value in that check, or there isn't.
- 2a. makes the metric a lot less useful, as generic alerts can't be defined
- 3. is out of the question, given the value of the metric
- 4. the ability to use PUT and replace all existing metrics and DELETE on the data of a single subtask is important to all our existing users of grouping labels

My vote would be 1a, then 2b.

**Comment by brian-brazil** [comment]
This will affect more than just `push_time_seconds`, any two groups with the same metric name will have the same issue.

1) represents our options, and I'm tending a bit towards removing a).

**Comment by grobie** [comment]
> This will affect more than just push_time_seconds, any two groups with the same metric name will have the same issue.

Yes, but a user has at least control over these. If we were to decide on strictly forbidding a metric to exist with varying label sets, they'd need to prefix all their metrics as well. It'd be quite cumbersome, especially as the error is only returned on pgw scrape, and I imagine not everyone uses a "one pgw per team" setup. Still possible though.

**Comment by brian-brazil** [comment]
In terms of the pgw, it's valid to have a metric from different groups with different labels. Groups are basically target labels.

**Comment by beorn7** [comment]
> In terms of the pgw, it's valid to have a metric from different groups with different labels. Groups are basically target labels.

This would still make the exposition of the PGW (i.e. what it serves under `/metrics`) inconsistent.

I previously suggested to relax the data model in the way the Prometheus server treats it anyway, i.e. allowing missing labels by implicitly assuming that all missing labels are there with an empty label. That was resisted, mostly by you, IIRC.

I don't think that making an exception for the PGW is sane, as the `/metrics` output has no formal differences to the `/metrics` output of any other target. Real target labels are attached by the Prometheus server. They are not on the wire. The folks that export K8s pod labels (or wherever that consistency problem arose earlier) could equally argue that their label set is special and should get an exception instead of adding empty labels that semantically don't make sense from their perspective.

**Comment by brian-brazil** [comment]
> That was resisted, mostly by you, IIRC.

My objection was to the specific implementation of having a 3rd type of registry in client_golang, and that the way it was proposed to work was a layering violation that would result in everyone eventually end up using the unchecked version - which defeats the purpose of the check and adds a gotcha for users. I've no problem with client_golang removing those checks outright (no other client checks this for custom collectors after all), but if the checks are there they should always be enforced in the registry.

> However, I can see how problematic that is during changing a metric to have different dimensions, and then having pushers running with different binary versions.

There's also the case where you have both an sharded and unsharded version of some batch job, so there's differing group labels.

> could equally argue that their label set is special and should get an exception instead of adding empty labels that semantically don't make sense from their perspective.

Yes, any reasoning here applies there too as they have a valid use case.

**Comment by beorn7** [comment]
> I've no problem with client_golang removing those checks outright (no other client checks this for custom collectors after all), but if the checks are there they should always be enforced in the registry.

The latter is the state, and that's the reason why the PGW cannot expose (presumably) invalid label dimensions.

In client_golang, metrics are gathered for exposition via the `Gatherer` interface, and all implementations of that interface ensure that the gathered metrics are consistent. (The most common implementation is the registry, which also implements the `Regesterer` interface, but there is also the `Gatherers` slice to merge multiple gatherers, which is used by the PGW to inject the pushed metrics.)

If you say we should either consistently have checks for label consistency or we should not have those checks, then either we check it for everything including the PGW, or we check it for nobody.

As suggested earlier, I'm kind of OK with simply allowing arbitrary label dimensions in expositions (with the premise that missing labels and labels with an empty value are equivalent). But in that case, we should make it formally clear that this is legal. Client libraries should only be able to produce legal expositions.

(In direct instrumentation, we could continue to enforce consistent label dimensions at registration time, as it was always the case.)

**Comment by brian-brazil** [comment]
> But in that case, we should make it formally clear that this is legal. Client libraries should only be able to produce legal expositions.

Something else to consider is that OpenMetrics will allow inconsistent exposition, basically because there are uncommon valid use cases like these for it.

The real thing the inconsistency checks buy us is catching a) users attempting to do event logging and b) using one metric when they should have many. Both should still largely be caught by the checks for label consistency on direct instrumentation.

**Comment by beorn7** [comment]
> Something else to consider is that OpenMetrics will allow inconsistent exposition, basically because there are uncommon valid use cases like these for it.

That's very good to know.

> The real thing the inconsistency checks buy us is catching a) users attempting to do event logging

Incidentally, one of the SoundCloud PGWs that ran into the consistency check problems after the update was doing so because the users tried event logging via the PGW...

> Both should still largely be caught by the checks for label consistency on direct instrumentation.

Unless you run it through different groups via the PGW... :o)

But agreed in general. I think we have clarity:

- Direct instrumentation will ensure label consistency at registration time.
- Custom collectors are allowed to create inconsistent label dimensions.

Next steps:

1. Clarify in the docs (format spec, client library) that inconsistent label dimensions are valid in the exposition format but client libraries should aim to enforce label consistency in direct instrumentation.
2. Change client_golang (simply remove the label consistency check in the implementation of `Gather`).
3. Update vendoring for PGW and release 0.5.2.
4. Rejoice!

**Comment by brian-brazil** [comment]
> Incidentally, one of the SoundCloud PGWs that ran into the consistency check problems after the update was doing so because the users tried event logging via the PGW...

Hopefully we'll catch those when they go looking for a TTL on metrics in the PGW. I'm a bit surprised we haven't heard more from timestamps no longer being supported actually.

> But agreed in general.

All sounds good.

> Clarify in the docs

The format already permits it, and that'll be a one line change in the client library docs to clarify the new state for custom collectors. Client libraries enforcing that for direct instrumentation is already mandatory.

**Comment by grobie** [comment]
Great, thanks for the input and discussion. Looking forward to v0.5.2. I assume you'll take care of that @beorn7?

**Comment by beorn7** [comment]
Yes, I'll work on all required steps today or at latest tomorrow.

**Comment by beorn7** [comment]
@grobie I'll wait for your report from SoundCloud production before closing this and cutting v0.5.2. Do you think you will get to it any time soon?

**Comment by grobie** [comment]
I'll do it early next week. Is the on-disk database format forward compatible? It's not backwards compatible (v0.3.1 will panic on trying to read a dump written by v0.5.1), and resetting the whole state caused concerns by teams.

**Comment by beorn7** [comment]
Yes, you can roll forward from any released version to what we have currently in master.

**Comment by grobie** [comment]
Installed today, looks good so far. If it's still running fine tomorrow, we can release 0.5.2 I think.

**Comment by beorn7** [comment]
Awesome. I'll probably have time for a release tomorrow evening.

**Comment by grobie** [comment]
Everything runs fine. Thanks for the fix, looking forward to v0.5.2 :-)

**Comment by beorn7** [comment]
This is fixed by #188 .
