### ISSUE TITLE
Frequent push data to pushgateway, data loss

### ISSUE THREAD

**Issue by sunchanglong1991** [prometheus/pushgateway#187]
> Use the push_to_gateway method in prometheus_client to send data to pushgateway. After the loop is sent. Prometheus queries have lost intermediate data.

> My understanding is: The client sends the data to pushgateway, then pushgateway collects the data and waits for Prometheus to pull the data regularly.Then the data should be saved. Pushgateway did not save the received data in time or has the pushgateway failed to support high frequency reception, resulting in the loss of intermediate data?  However, the pushgateway adopts the push method. According to the principle, this should not happen. Who can help me to answer this question?

`
#!/usr/bin/env python
# coding:utf8

from prometheus_client import start_http_server,Summary,Counter,Gauge,CollectorRegistry,push_to_gateway

import random
import time
import sys

def test_push_with_groupingkey(n,t):
	registry = CollectorRegistry()
	m = random.randint(1,100)

	g = Gauge('test_push', 'ce shi', registry=registry).set(m)
	push_to_gateway('localhost:9091', job="test",registry=registry)
	print "-------------------------\n"
	time.sleep(t)

if __name__ == '__main__':

	num = int(sys.argv[1])

	for n in range(0,num):
		test_push_with_groupingkey(n+1,1)

`
@beorn7

**Comment by beorn7** [comment]
The Pushgateway behaves correct here.

A push to the Pushgateway with the `PUT` HTTP method ovrewrites all metrics with the same grouping key. Thus, if your Prometheus server hasn't yet scraped the previously pushed metric, it is lost.

This behavior makes sense if you take into account what the Pushgateway is used for, see https://prometheus.io/docs/practices/pushing/ for details. Pushing the same metric to the Pushgateway every second is not what it is made for.

If you have more questions, I would encourage you to ask them on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
