### ISSUE TITLE
TTL for push group

### ISSUE THREAD

**Issue by tux21b** [prometheus/pushgateway#192]
Really guys? I know that there have been a lot of previous issues about TTL that have been closed because you consider it a anti-pattern to have a cache with an expiration mechanism. But since the issue isn't fixed yet and I can not comment on the previous issues because they have been locked i will give it another try.

**Scenario:**

I am currently monitoring AppEngine instances with Prometheus. I first tried to use the GCE Discovery, but unfortunately, AppEngine instances are not listed as GCE instances. Then I tried to write a manual discover script and used instance targeting (a feature where you can prefix your appspot.com URL with an instance-id to connect to a specific instance). Unfortunately instance targeting is only available with manual scaling. For dynamically scaled instances it is not possible to target them directly. The only solution was to let the instances push the metrics using the pushgateway.

It took me quite some time to discover that metrics, that are not available anymore, are still scraped by Prometheus as if they were new. A behavior of the push exporter that was unexpected, since it differs from the direct scraping approach. Then I thought the PushGateway probably just got the cache timings wrong because I haven't configured them explicitly (and some people might use it to send a batch job just once a day, which would require a high default TTL). I was extremely surprised that there were no TTL configured.  Something that I definitely did not expect!

So, here I am. Running a large cluster of dynamically scaled AppEngine instances that appear and disappear all the time, having trouble keeping up with pressing the rarely needed "delete group" and "confirm" buttons for instances that do not exist anymore.

**Comment by beorn7** [comment]
The best place to have this discussion is the [prometheus-developers mailing list](https://groups.google.com/forum/#!forum/prometheus-developers) rather than a GitHub issue. On the mailing list, more people are available to chime in, and the whole developer community can follow the discussion.

I'm closing this issue now, explicitly not to kill the discussion but to direct it to the correct channel.

Should the discussion result in the feature to be implemented, then the implementation details can be discussed in a GitHub issue.

**Comment by beorn7** [comment]
> I can not comment on the previous issues because they have been locked

I locked those issues because I have told people repeatedly to use the mailing list, which they decided to ignore.
