### ISSUE TITLE
How to get started with adding instrumentation

### ISSUE THREAD

**Issue by malarcon1** [prometheus/pushgateway#195]
Hello,
sorry if this seems like a silly question but I'm still confused about how to set up instrumentation and exporting of metrics- even after reading the guide about ten times. 

I followed the first part okay and on my Prometheus UI the endpoints are up and connected to my openshift services- the only thing I need to implement now is actually adding the instrumentation to my code. When I curl prometheus endpoint of my java service nothing is returned when I know something should be.

I have pasted the functions in a class called Prometheus.Java which is used by a Java servlet to connect to prometheus. However I'm not sure how these functions should be called or even declared.
Any help or guidance on this is much appreciated.

**Comment by beorn7** [comment]
Hi,

Your question doesn't seem to be related to the Pushgateway. Also, it makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided. The [community page](https://prometheus.io/community/) lists further channels to get support.
