### ISSUE TITLE
Understanding aggregation / events

### ISSUE THREAD

**Issue by SteveNewhouse** [prometheus/pushgateway#207]
Hello,

I believe your documentation touches on this but I wanted to make sure I understood it properly.  We have a use case where we'd like to track build times.  To do this, we envisioned a shell script on our CI server that'd push the duration into Prometheus via the pushgateway. 

Ultimately, we'd want to see aggregations of these build times, like averages, percentiles, etc... The documentation regarding pushgateway not being suitable for distributed counting / aggregation was directed as use cases like this?

Just wanted to double check before I investigate further.

**Comment by beorn7** [comment]
Tracking build times of individual builds is really an event logging use case. Prometheus is metrics-based and of limited use here.

Even if you shoehorn this somehow into metrics, I would still go for a solution where the CI server exports those metrics directly, either via a small exporter binary (perhaps one exists for your CI system already) or via the textfile collector of the https://github.com/prometheus/node_exporter .

In general, it makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

I'll close this issue. Please post to the mailing list if you want to know more.
