### ISSUE TITLE
Clarify documentation that DELETE only ever deletes by grouping key

### ISSUE THREAD

**Issue by praetp** [prometheus/pushgateway#225]
I think it's regrettable you cannot remove all metrics by only specifying the job.
Multiple people have run into this: (e.g. https://github.com/prometheus/pushgateway/issues/128, https://github.com/prometheus/pushgateway/issues/162).
The confusion is only increased because the documentation is not correct:
It still mentions in the README.md you _can_ delete metrics by job.

Not having this feature is annoying because sometimes you want to clear the old metrics without knowing what the grouping keys were.

**Comment by beorn7** [comment]
After a bit of reading, I see now where the documentation is misunderstanding. (At least I hope that's the part that was the cause of your confusion.) I'll create a PR.

WRT adding the feature: It's not as easy as you might think. `curl -X DELETE http://pushgateway.example.org:9091/metrics/job/some_job` will delete metrics pushed with `job="some_job"` as grouping key. It would be a breaking change if the same request suddenly also deleted other metric groups. Thus, we needed a separate method (or endpoint, or syntax) to do so. The next request will probably be that other parts of the grouping key can also be specified partially, e.g. "I want to delete all metric groups with `foo="bar"` in the grouping key". Which will then lead to the next level of confusion, because metrics with `foo="bar"` as a label but _not_ part of the grouping key will _not _ be deleted. I'd prefer to not open Pandora's box here, unless there is a compelling use case for it. The previous issues seem to have been caused by confusion, not by actual need to delete by parts of the grouping key.

**Comment by praetp** [comment]
Thanks for your prompt reply. The documentation is indeed not so clear and I look forward to your changes. OTOH, I was confused myself about the whole 'group' concept. Maybe doesn't hurt to add somewhere in the beginning what it means exactly.

**Comment by praetp** [comment]
It's a lot better now. Thanks.
