### ISSUE TITLE
An error shows that pushgateway collected a metric with same name and same label values

### ISSUE THREAD

**Issue by tony810430** [prometheus/pushgateway#232]
It seems that they were stored by different key, from labels in url path, but they both generated the same MetricFamily, and it led to this error. Am I right and is this the expected behavior? Thanks.

## Bug Report
**What did you do?**
```
$ cat <<EOF | curl -X POST --data-binary @- http://127.0.0.1:9091/metrics/job/some_job/tag/val1
> # TYPE some_metric counter
> some_metric 1
> EOF

$ cat <<EOF | curl -X POST --data-binary @- http://127.0.0.1:9091/metrics/job/some_job
> # TYPE some_metric counter
> some_metric{tag="val1"} 42
> EOF
```
**What did you expect to see?**
`some_metric` is updated correctly.

**What did you see instead? Under which circumstances?**
http://127.0.0.1:9091/metrics crushed
```
An error has occurred while serving metrics:

collected metric "some_metric" { label:<name:"instance" value:"" > label:<name:"job" value:"some_job" > label:<name:"tag" value:"val1" > counter:<value:1 > } was collected before with the same name and label values
```
**Environment**
latest docker version

**Comment by zemek** [comment]
@beorn7 I would like to request this issue be re-opened. It doesn't seem reasonable for users to be able to accidentally break the pushgateway by pushing metrics.

Instead of returning an error at scrape time, why couldn't we return an error to the client at push time?

For example if we tried to run 
```
echo 'my_metric 1' | curl -X POST --data-binary @- http://localhost:9091/metrics/job/my_job/tag/val
echo 'my_metric{job="my_job", tag="val"} 2' | curl -X POST --data-binary @- http://localhost:9091/metrics/job/my_job
```

the first push would succeed, but the second push would return an error, saying that the same name and label values already exist in a different group.

This seems like a more graceful way of handling this situation. What do you think?

**Comment by beorn7** [comment]
Yes, that's tracked in #202.

**Comment by circa10a** [comment]
This should at least not cause `/metrics` endpoint to crap itself.

**Comment by beorn7** [comment]
Please see #202 for dealing with this. Sadly, once invalid metrics have been accepted, it's really hard to act in a sane way. (“Crapping itself” might indeed be the best option in that case.) That's why the way out is to not accept those metrics in the first place.
