### ISSUE TITLE
请能看懂中文的朋友帮忙解答下

### ISSUE THREAD

**Issue by wuzhix** [prometheus/pushgateway#237]
test{host="www.test.com",instance="ins",job="job"} 1
test{host="www.aaa.com",instance="ins",job="job"} 0
现在pushgateway有这样的数据，我想将job的数据全部删除掉，用curl -X DELETE http://127.0.0.1:9091/metrics/job/job 和 curl -X DELETE http://127.0.0.1:9091/metrics/job/job/instance/ins 都没有效果，必须得用curl -X DELETE http://127.0.0.1:9091/metrics/job/job/instance/ins/host/www.test.com 才能删除掉，但是我又成千上万条这样的数据，一条一条的删太坑了吧

**Comment by javabrett** [comment]
This behaviour is per the documentation.  I think you will need to read-back all the current grouping keys and issue a `DELETE` per entry.

**Comment by beorn7** [comment]
@javabrett thanks for reading the Chinese.

To add on this: It looks like you had been using a too detailed grouping key. Usually, just the `job` label is sufficient as a grouping key.

In general, it makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided. The mailing list is in English, though. I don't know if any Prometheus user forum exists in Chinese.

In any case, we don't use GitHub issues for usage questions. Thus, I'm closing this.
