### ISSUE TITLE
pushgateway metric timeout and perfomence report issues?

### ISSUE THREAD

**Issue by DemoLiang** [prometheus/pushgateway#238]
## Feature request
**Use case. Why is this important?**
1. maby ,when our endpoint no longer pushe data, the job/endpoint should be timed out automatically.? timeout we should be able to configure.
2. whether pushgateway has a performance report, how many metrics we can push? 

*“Nice to have” is not a good use case. :)*

**Comment by beorn7** [comment]
1. About the timeout, please refer to the last paragraph of https://github.com/prometheus/pushgateway#non-goals .
2. There is no fixed limit to the number of metrics you can push. You can use the exported Prometheus metrics to observe CPU time, memory need, and much more to get an idea how many resources you need. However, if you are pushing more than a handful of metrics, the odds are you are doing something wrong. The Pushgateway is not suitable to turn Prometheus into a push-based metrics collection system. See also https://prometheus.io/docs/practices/pushing/

In general, it makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

Thus, I'm closing this issue here.
