### ISSUE TITLE
feature request: cluster

### ISSUE THREAD

**Issue by danielmotaleite** [prometheus/pushgateway#241]
## Feature request

Right now push gateway  do not support any HA capability, the best we can do is run several push gateway and publish then in a load-balancer, but if any push-gateway dies (crash, mistake, host problem), any data in it is lost. It also requires that prometheus read from all push-gateway to get all the metrics. Alternative is to push the metric to each push gateway, but that is not always possible  (app limitation, routing issues, etc) and we end with duplicated metrics that may break alerts and metric analysis.

So the good solution would be to add a cluster capability similar to the alertmanager, where each node will share their state with the remaing cluster nodes and if one of then dies, the data is still there. The load balance could still be used to write, keeping always some push gateway running, but also to read the metrics, keeping the correct number of events from whatever node we are reading from

**Comment by beorn7** [comment]
Well, yes. The HA story of the Pushgateway essentially doesn't exist. The excuse is that the PGW is not meant to turn Prometheus into a push-based monitoring system, but to “cache” metrics of ephemeral jobs. If the PGW goes away, the applicable flavor of orchestration you are using should spin up a new one, and once all those ephemeral jobs have run again, all is good again. For most use cases, alerting on the ephemeral jobs doesn't require quick responses, so missing a cycle because the PGW got rescheduled should be (borderline-)acceptable.

Of course, I can totally see how annoying that still is, but take into account how complicated a clustered PGW will be, with all its new and surprising/exciting failure modes it will provide. Thus, my intuition is that the cost/benefit ratio is quite high here. Unless, of course, you are in the camp of “PGW abusers” who actually use the PGW to turn Prometheus into a push-based monitoring system. But that's explicitly a non-goal within the Prometheus project as a whole.

I don't want to reject this proposal outright. But keep in mind that, should it be implemented within the core Prometheus project, their needs to be some level of agreement across the project that the effort make sense within the “proper” way of using Prometheus. (Needless to say that people can do whatever they want on their own outside of the project.)

Another intuition is telling me that this should probably be implemented separately at first, as an experiment, similar to the “distributed counter use-case” (see README.md). Should that present a way to easily integrate it in the PGW, great. But it might as well turn out to better be kept separate to retain the current PGW as the very easy and lightweight thing it is, even if it only caters for a sub-set of possible use-cases.

**Comment by danielmotaleite** [comment]
I understand that PGW is just a workaround for simple things, not really a full important product... but in my user case, those jobs using it are important, they are related to payment, so losing a PGW is both bad because i lose any metric still not read by prometheus and may fail to receive any new payment metric while the service is not back up. That can generate alerts and make everyone panic. They are rare events, but they happen.
Sadly that system only support one push notification endpoint and no pull endpoint, so getting a better PGW would be great! :)

**Comment by beorn7** [comment]
The dissonance in this is that Prometheus was not designed as a lossless system. On the contrary, everything takes into account and accepts that scrapes might not happen, counters might get reset (with a certain amount of events not counted) and so on. Using Prometheus for payment-related data is not recommended.

In any case, this all really feels like a distributed, fail-safe pushgateway should be a different beast from this existing Pushgateway.

**Comment by danielmotaleite** [comment]
i think i didn't explain well enough, i'm talking about payment **metrics** in PGW (like number of query and post calls, how many success, how many failed, how many it security filters). I'm **not** using it for the payments itself! :)

Any hiccup in PGW make the metrics in grafana jump up and down in weird ways and due to the importance of the metric, everyone always notice those problems. It can also generate fake alerts in the payment service, where the problem is really in the metric setup.
To make this worse, our current orchestration method is slow to react, so more redundancy would help a lot. Even if losing some events are possible, that is not that critical as having no metrics for some time.

How about a "simple" cluster where one PGW would give it own metrics, but would also fetch and deliver any other metrics other "cluster nodes" could have.

example: 3 nodes, i can add a loadbalancer(lb) to then and services would push the metric to the lb and so to one of the PGW. Then prometheus would consume from the lb, the PGW that would receive the metric request would query the other known nodes for metrics and deliver then. Any unresponsive node would timeout and the node that have the query would return whatever it could find. Most of the work in in the lb, PGW would only need to do a recursive query to any dns/list of nodes, if needed... "should be simple™" ( _i know, i know, i'm not a programmer, so it's always simple when we know nothing about the topic!_) :smile:

**Comment by beorn7** [comment]
:phew: about not using Prometheus for the actual payments. :smile: 

Your case really feels like the monitored system should support getting scraped to play nicely with Prometheus. (Have you considered the exporter pattern? You would create a little sidecar on each instance of the service to monitor. The sidecar contains a little binary, scrapeable by Prometheus. It serves the metrics, either by collecting them on the spot or by having them received from the monitored service instance before. The lifecycle of the sidecar is bound to each instance of the service, and thus you don't have the problems with dying nodes anymore.)

Even the "simple" clustering you describe is probably an order of magnitude more complex than what the PGW is right now. And despite all the effort, you might simply end up with the worst of both worlds, i.e. the problems of a push-based system combined with the problems of a pull-based system.

I guess any stab at this had to happen separately for a while (as a fork, if need be). To eventually merge it into the normal PGW, the result had to fulfill certain criteria:
- Support the intended use cases of the PGW (rather than turning Prometheus into a push-based monitoring system).
- Normal operation of the PGW has to stay as simple as it is.
- Complexity has to stay low enough that code maintenance, feature development etc. isn't much harder than before.

I'd like to see a good HA story for the PGW, but I don't see a simple way yet to do it "just as a PR" here in the repo.

**Comment by kklipsch** [comment]
What would a side car pattern look like for something like an EMR job?  Doesn't that have all the same problems as the pushgateway?

**Comment by beorn7** [comment]
I assume EMR == https://aws.amazon.com/emr/ .

That's essentially a batch job for which a sidecar that gets scraped wouldn't work. However, I understood @danielmotaleite 's use case as using the PGW for a job that is essentially running permanently and does have an urgent requirement of real-time metrics. For the typical batch job scenario, the current PGW works fine. Or let's say "good enough'. If you have a strict requirement of transactionally delivering some piece of data at the end of your batch job, than Prometheus isn't a good fit even if there was some kind of clustered HA Pushgateway.

On a general note, I would like to keep this issue to the implementation of an HA feature for the PGW (if possible at all within the scope of this repository). Discussing various use cases including possible work arounds or better approaches should better happen on the [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users). On the mailing list, more people are available to potentially take part in the discussion, and the whole community can benefit from the answers provided.

**Comment by beorn7** [comment]
After half a year of time to consider, I'm fairly certain that the feature discussed here isn't going to happen anytime soon within the PGW as we know it. Now that we have v1.0.0 of the PGW, I would like to close this issue, mainly to not create a false impression that this is a feature somehow in the pipeline.

This should not discourage people from creating a clustered equivalent of a Pushgateway (which might also be a good solution to the “distributed counter” use case). It should just happen as a separate project. If the future proves me wrong then and we can later merge it all into one project, so much the better. For now, it's just something we really shouldn't aim for.
