### ISSUE TITLE
Delete data old than 10 days

### ISSUE THREAD

**Issue by sivalearn12** [prometheus/pushgateway#255]
Hi,
i have pushed the data to prometheus via pushgateway and using grafana to show the pushed data using prometheus. In resolve the memory issue , i need to delete the data older than 10 days in pushgateway. i have set the storage retention time interval as 10 days in prometheus which is not reflecting for pushgateway data. Kindly guide me how to delete the data older than 10 days in pushgateway.

Thanks

**Comment by beorn7** [comment]
The Pushgateway has deliberately no built in mechanism to delete pushed data longer than 10d.

See last paragraph of https://github.com/prometheus/pushgateway#non-goals and the thread on the prometheus-developers mailing list: https://groups.google.com/forum/#!topic/prometheus-developers/9IyUxRvhY7w

If you need further support, please ask on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
