### ISSUE TITLE
Delete the metric generated via pushgateway using exported_job

### ISSUE THREAD

**Issue by sivalearn12** [prometheus/pushgateway#256]
Hi,
i have generated custom metric with exported_job via pushgateway. is it possible to delete the metric using exported_job curl -X DELETE http://localhost:9091/metrics/exported_job/testing_interval instead of "curl -X DELETE http://localhost:9091/metrics/job/testing"

**Comment by sivalearn12** [comment]
i tried with label value pair also.. its not workin ..curl -X DELETE http://172.30.1.91:9091/metrics/job/testing{/keyvalue/testing_W2}

here testing is  job and keyvalue is label name and testing_W2 is the label value.

**Comment by sivalearn12** [comment]
A PUT request with an empty body effectively deletes all metrics with the specified grouping key as per the documentation. Can you please guide me with sample. So that i can try for the use case. i need to delete the metric in the pushgateway using metric name and label value pair. Please guide me.

**Comment by beorn7** [comment]
You can only delete by grouping key.

To get more support, please use the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by sivalearn12** [comment]
Thanks.
