### ISSUE TITLE
Pushgateway 500 on histograms

### ISSUE THREAD

**Issue by mwitkow-io** [prometheus/pushgateway#26]
It seems that the latest Pushgateway from docker `prometheus/pushgateway:latest` doesn't support histograms. When you push data with histograms it barfs with an error 500. Additionally, the error message is not very helpful, and there are no logs for Pushgateway.

**Comment by beorn7** [comment]
Histograms are only supported with the newest version of the client lib. I assume that docker image is still built with the old version (and to be fair, Pushgateway didn't get a version bump, because the change only happened in the dependencies).

If you do `go get -u` or (in make terms) `make clean && make build`, it works. (The status web page will not render histograms properly, which is something I have to fix eventually.)

@discordianfish Is there a step to be done to update the Pushgateway as it comes "from Docker"? Sorry for being so Docker illiterate...

**Comment by discordianfish** [comment]
@beorn7 The images should get rebuilt on every push to their github repo. Rebuilds because a dependency needs to be updated like in this case, need to be triggered manually.
@juliusv has access to that as well. If you like, you can sign up on hub.docker.com and I can add you to the 'prom' org so you can do that as well.

**Comment by beorn7** [comment]
Understood. We'll want to vendor the dependencies into pushgateway soon, anyway, so that will also solve the automation problem.

Thanks @discordianfish . Have you triggered a build now? Or @juliusv , could you do it to fix the immediate problem?

**Comment by juliusv** [comment]
I logged in there, but there is no "do a build button" anywhere...

**Comment by discordianfish** [comment]
I've triggered the build but still waiting.
@juliusv: You see no "Start a Build" button here? https://registry.hub.docker.com/u/prom/pushgateway/
Maybe this is only allowed to Docker staff..

**Comment by juliusv** [comment]
Yep, no button for me. Username "julius".

**Comment by beorn7** [comment]
Thanks @discordianfish for triggering the build. The other issues touched here have own issues, so closing this one.
