### ISSUE TITLE
How to config the access controll of pushgateway

### ISSUE THREAD

**Issue by nevenchen** [prometheus/pushgateway#281]
Currently I set my pushgateway without any access controll, Anyone can push data to my application without any authorization.
When I use the java client, I found that it have a way to set a password as bellow:
`

    pushGateway = new PushGateway("localhost:" + mockServerRule.getHttpPort());
    pushGateway.setConnectionFactory(new BasicAuthHttpConnectionFactory("testUser", "testPwd"));
`
The question is , How can I set a access acount for my pushgateway?

**Comment by beorn7** [comment]
You have to set up a reverse proxy in front of Pushgateway.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
