### ISSUE TITLE
scrape data from pugateway error

### ISSUE THREAD

**Issue by wanghonglei5181** [prometheus/pushgateway#289]
## Bug Report
**What did you do?**
```
i pushed a metrics with value 0,
the prometheus can not scrape data from pushgateway!
send a alert like "instance pushgateway down "
```
**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:
```
Linux 4.16.12-toa1.el7.centos.x86_64 x86_64
```
* Pushgateway version:
```
pushgateway, version 0.9.1 (branch: HEAD, revision: b4410a3a361a770a084007ef50aebf42d0e8793c)
  build user:       root@556a5d403380
  build date:       20190801-14:03:20
  go version:       go1.12.7
```

* Pushgateway command line:

./pushgateway --log.level=error

* Logs:
```
120 error(s) occurred:
* collected metric "value" { label:<name:"hostname" value:"cx003.cre.sx.node.com" > label:<name:"idc" value:"sx" > label:<name:"instance" value:"sx-cx003.cre.sx.node.com" > label:<name:"job" value:"cre_rsyslog_status" > label:<name:"key" value:"" > label:<name:"product" value:"testssss" > label:<name:"topic" value:"rsyslog_main" > untyped:<value:0 > } was collected before with the same name and label values
```

**Comment by beorn7** [comment]
You probably pushed the same metric to two different groups. You can check the UI for those groups and delete offending groups. This is most likely not a bug but a problem with your usage. It makes more sense to ask usage questions on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided. If you cannot solve the problem, please ask on the list.
