### ISSUE TITLE
Add Pushgateway container images to prometheus org on Quay

### ISSUE THREAD

**Issue by aditya-konarde** [prometheus/pushgateway#307]
## Feature request
**Use case. Why is this important?**

Currently, the pushgateway images are pushed to Docker hub:
https://hub.docker.com/r/prom/pushgateway

I see that many other Prometheus images are available in https://quay.io/organization/prometheus

RFE: We should try to maintain consistency by making the pushgateway exporter images also 
available in the Prometheus organization in Quay.

Please let me know if a mail thread is a better place to track this ;)

PS: I haven't checked yet, but this might be as simple as doing a skopeo copy in the post-build step to get started with

**Comment by aditya-konarde** [comment]
Added a similar one for cloudwatch exporter: https://github.com/prometheus/cloudwatch_exporter/issues/220

**Comment by beorn7** [comment]
Yeah, this should be easy.

**Comment by oliviermichaelis** [comment]
As far as I understood, the pushgateway images are already getting pushed to the [quay.io/repository/prometheus/pushgateway](https://quay.io/repository/prometheus/pushgateway) repository.
I couldn't comprehend why multiple repositories for the different architectures exist in Quay, though. For example 
`prometheus/pushgateway-linux-amd64`, `prometheus/pushgateway-linux-arm64`, `prometheus/pushgateway-linux-armv7`.

In addition, the manifest list of `prometheus/pushgateway:master` contains the same images with the same digests as `prometheus/pushgateway-linux-arm64:master` already. It's just, that the architectures are set to `amd64` instead of the respective correct architectures (e.g. `arm64`).
Should I open a new issue for that?

Would be nice to get some feedback, since I'd be interested in resolving that :)

**Comment by oliviermichaelis** [comment]
I just had a little bit of spare time and came up with a possible solution:
* Tag the docker images built for the specific architectures according to the following scheme: `$(DOCKER_REPO)/$(DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_TAG)-$(ARCH)`
* Push those docker images to the repository
* Create docker manifest list and annotate each manifest with the respective architecture
* Push the created manifest list to `$(DOCKER_REPO)/$(DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_TAG)`

I just tried that out as a proof of concept and pushed it to [my docker hub repository](https://hub.docker.com/r/oliviermichaelis/pushgateway).
Please note, that the `master` tag manifest now contains the multiarch information for all 3 architectures.

This approach would channel all docker images into a single repository instead of 4 and provides the right architecture on a docker pull in a multi-arch fashion.

I can offer to create a new issue as well as a PR for that :)

**Comment by beorn7** [comment]
Thanks for the research @oliviermichaelis . Whatever we are dong, it should be in line with what's done in the prometheus/prometheus GH repo. That means:

- If something here in prometheus/pushgateway is different from the way it is done in prometheus/prometheus, we should bring prometheus/pushgateway in line with prometheus/prometheus.
- However, if something is problematic with the way prometheus/prometheus is doing it, too, we should fix it there first and pull things down here afterwards.

**Comment by oliviermichaelis** [comment]
Thanks for those pointers @beorn7 !
I created PR #310 for the issue regarding wrong architectures in the docker manifest list.

**Comment by beorn7** [comment]
`docker pull quay.io/prometheus/pushgateway:v1.0.1` works for me now, and thanks to #310, it should also work on all architectures.
Please follow up if you still see issues.
