### ISSUE TITLE
How to protect pushgateway api with username and password?

### ISSUE THREAD

**Issue by sankar1204** [prometheus/pushgateway#317]
## Feature request
**Use case. Why is this important?**

*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

		Insert output of `uname -srm` here.

* Pushgateway version:

		Insert output of `pushgateway --version` here.

* Pushgateway command line:

		Insert full command line.

* Logs:
```
Insert Pushgateway logs relevant to the issue here.
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
