### ISSUE TITLE
Pushgateway HA

### ISSUE THREAD

**Issue by ssup2** [prometheus/pushgateway#319]
Hi, I want to run Pushgateway with HA. I find some about Pushgateway HA at below 
* https://github.com/prometheus/pushgateway/issues/241

Referring to the link above, I thinks 2 ways.
1) Batch Job --> LB --> Pushgateways --> Prometheus Server
2) Batch Job (broadcast metric to all Pushgateways)--> Pushgateways --> LB --> Prometheus Server

I thinks 1) is simple but it could be lost metric info. And 2) is hard to set but it could be reduce the loss of metric info. My question is that is there problem to run Pushgateway with 1) or 2) ways??

**Comment by beorn7** [comment]
Unfortunately, the Pushgateway doesn't really have a good HA story.

A discussion how to approximate HA best with the existing PGW should better happen on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to take part.

We use GitHub issues to track bugs and feature requests but not for usage discussions.

**Comment by ssup2** [comment]
@beorn7 Thanks your reply.

**Comment by ning1875** [comment]
https://github.com/ning1875/dynamic-sharding  have a look at this

**Comment by jcdauchy** [comment]
@ning1875 would you mind doing an readme in english of your project ?

**Comment by ermazi** [comment]
> https://github.com/ning1875/dynamic-sharding have a look at this

哪都有你，无处不在
