### ISSUE TITLE
Delete all indicators regularly

### ISSUE THREAD

**Issue by guleng** [prometheus/pushgateway#337]
## Feature request
**I think we can delete all the indicators every few minutes, can we achieve it?**

**Comment by beorn7** [comment]
What do you mean by “indicators”? If you are asking about timing out metrics after a while and delete them, please read the last paragraph of the [non-goals section](https://github.com/prometheus/pushgateway#non-goals).

**Comment by guleng** [comment]
@beorn7   I mean to delete all the data in pushgateway every few minutes. I saw that the delete method can only delete one data, because there are 150000 pieces of data in my pushgateway that need to be deleted

**Comment by beorn7** [comment]
The [Admin API](https://github.com/prometheus/pushgateway#admin-api) gives you an endpoint to wipe the whole storage. If you really wanted to, you can write your own automation to do so regularly. However, you are probably using the PGW in a way it isn't intended to be used.

That's why having this kind of auto-expiry is an explicit [non-goal](https://github.com/prometheus/pushgateway#non-goals).
