### ISSUE TITLE
Feature request: make pushgateway honor tiemstamps

### ISSUE THREAD

**Issue by wxiaoguang** [prometheus/pushgateway#338]
## Feature request

I have read your thoughts about why pushgateway doesn't accept metric timestamps.

Here is my situation why `honor_timestamps` in pushgateway is a necessary in our environment:

1. We have hundreds servers in different data centers/networks, some servers are connectable from the core data center, but others not.

2. We have many customized metrics which are collected by different utilities (eg: shell / CLI tools), some metric collection jobs take tens of seconds to be done. Since the collection time can not be predicted, we can not find a best value for `scrape_interval` in Prometheus server. We still hope Prometheus can scrape as fast as possible, so we still use scrape_interval=15s

3. The easiest (maybe only) choice for us is to deploy many pushgateways, make every server pushes their metrics to their connectable pushgateway, and make the Prometheus in core data center collect metrics from these gateways. 

4. Why ServiceDiscovery/PushProx doesn't work: `Textfile Collector` without timestamps can not resolve the long-run job problem (see below). (and another reason: some servers' resource are limited, we do not want to install node exporter on each server)

**Use case. Why is this important?**

Since the metrics are not guaranteed to be ready at the same time, if pushgatway doesn't hornor metric timestamps, the graph will be wrong. For example:

Some metrics are collected at time:

```
my_metric1 1000 {t}
my_metric2 1007 {t+7s}
```

pushgateway records as 

```
my_metric1 1000 {t+8s}
my_metric2 1007 {t+8s}
```

next time we collect metrics:

```
my_metric1 1060 {t+60s}
my_metric2 1061 {t+61s}
```

pushgateway records as 

```
my_metric1 1060 {t+62s}
my_metric2 1061 {t+62s}
```

The expected rates of both metric1 `(1060-1000)/60s` and metric2 `(1061-1007)/(61s-7s)` should be `1`

But the pushgateway changed the timestamp, and Prometheus get wrong rate: metric1 `(1060-1000)/(62s-8s)` and metric2 `(1061-1007)/(62s-8s)`. In our real case, the result is very wrong.

I have tried to comment out the `timestampsPresent` check ( https://github.com/prometheus/pushgateway/blob/master/storage/diskmetricstore.go#L359 ), everything just works as expected.

Indeed, since Prometheus supports `honor_timestamps`, I think it's good to give end users a chance (a CLI flag) to make pushgateway also honor the timestamps.

Thank you very much.

**Comment by beorn7** [comment]
With the way Prometheus handles staleness, timestamps exposed by the PGW are essentially broken. You can get away with it if you push more frequently than you scrape, but that's exactly the use case the PGW is not meant to be used for. (Turning Prometheus into a push-based system.) 

While your solution might work for you, it is a very brittle setup. Please understand that we don't want to add features to the PGW that can only be used for setups we do not recommend to use. Luckily, it's open source, so you can just patch PGW to make it support your use case for as long as it works for you.

If you want to discuss this further, I recommend to bring the discussion to the [prometheus-developers mailing list](https://groups.google.com/forum/#!forum/prometheus-developers) because you are proposing to revert a feature decision that we collectively made previously, and also this proposal touches more than just the PGW but also fundamentals about when to use timestamps at all and how it interacts with the staleness handling by the Prometheus server.
