### ISSUE TITLE
how to distinguish sanme name metric with different label

### ISSUE THREAD

**Issue by like-inspur** [prometheus/pushgateway#347]
**What did you do?**
first time push two same name metric which one with one label and another not with label 
```
root@mgt01:~# cat <<EOF | curl --data-binary @- http://10.110.19.60:9091/metrics/job/some_job/instance/some_instance
> some_metric{label="val1"} 42
> some_metric 3
> EOF
```
second time push two same name metric whici one with one label and another with another label
```
root@mgt01:~# cat <<EOF | curl --data-binary @- http://10.110.19.60:9091/metrics/job/some_job/instance/some_instance
some_metric{label="val1"} 42
some_metric{label="val2"} 43
EOF
```
**What did you expect to see?**
firsh time I think pushgateway will output error like duplicate metric
second time I think metric not with label first time pushed will be reserved

**What did you see instead? Under which circumstances?**
firsh time there are two metric can be found in pushgateway like below
![image](https://user-images.githubusercontent.com/18571465/81883350-8e7feb80-95c7-11ea-9a5c-08f580daf7c1.png)
second time two new metric override two old metirc firsh time pushed like below
![image](https://user-images.githubusercontent.com/18571465/81883565-2251b780-95c8-11ea-8591-bc685fd179b0.png)

* Pushgateway version:
1.2.0

**Comment by beorn7** [comment]
That's the intended behavior. If you push with the POST method, all metrics with the same name as the pushed metrics will be replaced, see https://github.com/prometheus/pushgateway#post-method .

If you have further questions, please ask on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
