### ISSUE TITLE
hello，the question i hava is when i use java-client to pushadd data,the response is "java.io.IOException: Response code from http://app-monitor-01.mjcndc01.com:9091/metrics/job/CountMetrics was 200",my pushgateway version is 1.10.0,but when i change this to 0.6,this issue is take down

### ISSUE THREAD

**Issue by zupermanOK** [prometheus/pushgateway#352]
## Feature request
**Use case. Why is this important?**

*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

		Insert output of `uname -srm` here.

* Pushgateway version:

		Insert output of `pushgateway --version` here.

* Pushgateway command line:

		Insert full command line.

* Logs:
```
Insert Pushgateway logs relevant to the issue here.
```

**Comment by beorn7** [comment]
I'm not sure I understand your question, but it anyway makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by zupermanOK** [comment]
appreciate u answer me,thanks
