### ISSUE TITLE
In what kind of ways you guys push data to pushgateway except curl?

### ISSUE THREAD

**Issue by FruitSamurai** [prometheus/pushgateway#357]

**Comment by FruitSamurai** [comment]
I use java, so I tried to use java libraries like HttpClient, OkHttp, but I found that only if I post a file which contained metrics, the pushgateway server responsed success!  I thins this is crazy. Anyone who can give me an example not file way? I would very appreciate it!

**Comment by beorn7** [comment]
We ladies would usually use one of the Prometheus instrumentation libraries, like e.g. http://prometheus.github.io/client_java/io/prometheus/client/exporter/PushGateway.html

In different news, it makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
