### ISSUE TITLE
Can we Auto Scale PushGateway-Prometheus Horizontally ?

### ISSUE THREAD

**Issue by vidurgupta** [prometheus/pushgateway#359]
## Feature request
**Use case. Auto Scaling the Push gateway on the basis of load**

**Comment by beorn7** [comment]
The Pushgateway is not designed to be scaled horizontally. I recommend to set up dedicated Pushgateways for different jobs pushing to it. Also, if you use the Pushgateway so heavily that you actually need to scale it horizontally, you are probably using it for something it is not intended for (and therefore cannot do well by design).

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
