### ISSUE TITLE
How to push non-float data?

### ISSUE THREAD

**Issue by lijingzhuang** [prometheus/pushgateway#373]
When using the pushgateway method, the script file written according to the document cannot push non-float data values. I would like to ask how to solve this problem?

**Comment by beorn7** [comment]
Prometheus metrics only ever have a float value. You can put string values in labels and use 1 as a label, fore example https://www.robustperception.io/exposing-the-software-version-to-prometheus .

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by lijingzhuang** [comment]
How to put multiple String types into one label, such as the three String types of data application_id, user, and queue.Thanks
