### ISSUE TITLE
histogram with _count pushed metrics are invalid or inconsistent with existing metrics but _bucket{le="+Inf"} works

### ISSUE THREAD

**Issue by kvbik** [prometheus/pushgateway#387]
## Bug Report
**What did you do?**
Trying to push data from Geth (Ethereum node). eg `geth --http --metrics --pprof --pprof.port 9545`

**What did you expect to see?**
Once pulling the metrics from `localhost:9545/debug/metrics/prometheus/` we got a number of histogram data, eg:
```
# TYPE chain_account_commits_count counter
chain_account_commits_count 33657

# TYPE chain_account_commits summary
chain_account_commits {quantile="0.5"} 0
chain_account_commits {quantile="0.75"} 0
chain_account_commits {quantile="0.95"} 0
chain_account_commits {quantile="0.99"} 0
chain_account_commits {quantile="0.999"} 0
chain_account_commits {quantile="0.9999"} 0
```

This should be consumable by Prometheus.

**What did you see instead? Under which circumstances?**

Instead we get an error saying:

`pushed metrics are invalid or inconsistent with existing metrics`

`collected histogram or summary named "chain_account_commits" collides with previously collected metric named "chain_account_commits_count"`

According to Prometheus documentation about histograms [1], I've tried to change `chain_account_commits_count` to `chain_account_commits_bucket{le="+Inf"}` and *push-gateway* accepted that without any issues!

[1] https://prometheus.io/docs/concepts/metric_types/#histogram

**Environment**

* Pushgateway version:

docker `prom/pushgateway`

. | .
-- | --
branch | HEAD
buildDate | 20210122-23:54:24
buildUser | root@410bc05a48f6
goVersion | go1.15.7
revision | 007ba874bead1b9ad2253d89e3adeb16a73fd012
version | 1.4.0

**Comment by beorn7** [comment]
Yeah, so you are running into an awkward problem with the Prometheus data model.

For one, there is the actual idea of the data model, which has counters and gauges and summaries and histograms. The latter two are "complex" metrics with quantiles and buckets and a _sum_ "field" and a _count_ "field". This is modeled properly in the (now effectively obsolete) original protobuf exposinios format.

It is modeled rather badly in the text format, and it is modeled in a similar way (and similarly bad way) by Prometheus internally. What happens is that the "complex" metric types are flattened into a number of "simple" metrics, using "magic" label names (like `quantile` or `le`) and "magic" name suffixes like `_count`, `_sum`, `_bucket`. I always saw that as a big and fat and very ugly wart of Prometheus.

So what's happening above is the following:

First look at this:

```
# TYPE chain_account_commits summary
chain_account_commits {quantile="0.5"} 0
chain_account_commits {quantile="0.75"} 0
chain_account_commits {quantile="0.95"} 0
chain_account_commits {quantile="0.99"} 0
chain_account_commits {quantile="0.999"} 0
chain_account_commits {quantile="0.9999"} 0
```

This is a summary, which _should_ have two additional "fields", namely `chain_account_commits_count` and `chain_account_commits_sum`. You don't provide them here, which is legal, but in the data model, they are still "reserved". That's why the PGW rejects the following:

```
# TYPE chain_account_commits_count counter
chain_account_commits_count 33657
```

If you just change the name to `chain_account_commits_bucket{le="+Inf"}`, you don't get the collision as this name would only be reserved for a histogram (which you didn't use).

Maybe Prometheus 2.x would accept your exposition, but that's because it tries to be tolerant – and also because it is pretty much ignoring metric types (which might change in the future, in which case it had to reject your exposition, too, as the PGW does already). Essentially, the PGW embraces the Prometheus data model more closely than the Prometheus server itself right now, so it depends more strictly on a valid exposition.

The best way to fix your metrics is to make your exposition look like this:

```
# TYPE chain_account_commits summary
chain_account_commits {quantile="0.5"} 0
chain_account_commits {quantile="0.75"} 0
chain_account_commits {quantile="0.95"} 0
chain_account_commits {quantile="0.99"} 0
chain_account_commits {quantile="0.999"} 0
chain_account_commits {quantile="0.9999"} 0
chain_account_commits_count 33657
```

PGW behaves as intended here. May I suggest to file an upstream issue with geth?

**Comment by kvbik** [comment]
Wow! Thx for the explanation @beorn7 ! I haven't even realised the "comments" in the metrics output has a meaning! :D I will do my best to bring this to Geth team's attention. Thank you once again, as it is expected behaviour I am going to close this. But will keep it as reference.
