### ISSUE TITLE
pushgateway write large number pushdata.in_progress.xxx file

### ISSUE THREAD

**Issue by ssyuan** [prometheus/pushgateway#398]
Hi, we have deployed 3 gateways for about 2 weeks now and recently the disks keep getting written to. Discovery log at the end.
There are many more pushdata.in_progress.xxx files inside the program directory, will these files replay on reboot?
How should I handle this situation better? Delete it directly?
**Environment**

* System information:

    Linux 4.19.91-22.2.al7.x86_64 x86_64

* Pushgateway version:

  build user:       root@410bc05a48f6
  build date:       20210122-23:54:24
  go version:       go1.15.7
  platform:         linux/amd64

* Pushgateway command line:

		./pushgateway --web.listen-address=:9191 --persistence.file=./pushdata --persistence.interval=1m

* Logs:
```
021/04/12 22:31:37 http: Accept error: accept tcp [::]:9191: accept4: too many open files; retrying in 20ms
2021/04/12 22:31:37 http: Accept error: accept tcp [::]:9191: accept4: too many open files; retrying in 5ms
2021/04/12 22:31:37 http: Accept error: accept tcp [::]:9191: accept4: too many open files; retrying in 10ms
```

**Comment by beorn7** [comment]
The pushdata.in_progress.xxx files are remnants from failed persistence attempts. Perhaps they fail because you have too many open files, as the log message says (that's also network connections, so perhaps hanging pushes consume all the file handles, and then persistence fails). Or your disk is full? In any case, your system seems to be in a bad state.

Are you perhaps pushing way too many metrics to the PGW?

**Comment by beorn7** [comment]
Assuming you are overloading the PGW, I'm closing this.
