### ISSUE TITLE
Editing script bash file 

### ISSUE THREAD

**Issue by elderwann** [prometheus/pushgateway#417]
Hello,

I try to write script bash file to push metrics from raspberry (cpu_usage process), but this file doesn't work..
I don't find script bash examples on the web to help me. Is anyone have some examples please ?

Here is my script bash file : 

`#!/bin/bash
z=$(ps aux)
while read -r z
do
	var=$var$(awk '{print "cpu_usage{process=\""$11"\", pid=\""$2"\"}", $3z}');
done <<< "$z"
curl -X POST -H "Content-type: text/plain" --data "$var" http://localhost:9091/metrics/job/top/instance/machine`

Thanks a lot.

**Comment by beorn7** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or our [forums](https://discuss.prometheus.io) rather than in a GitHub issue. In our [community channels](https://prometheus.io/community), more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
