### ISSUE TITLE
String is getting trimmed

### ISSUE THREAD

**Issue by mihaimyh** [prometheus/pushgateway#421]
I am pushing metrics such as
`cpu_usage{process="dsapi_slave",pid="89543"} 0.1`

But in Prometheus I see the process as `dsapi_sla+` instead of the original pushed name `dsapi_slave` (notice trimming happening by adding the + sign):

`cpu_usage{environment="DEV", exported_instance="machine", exported_job="top", instance="someServer", job="Engine", pid="89543", process="dsapi_sla+", source="push_gateway"}`

Any hints about this?

**Comment by mihaimyh** [comment]
This seems to happen when the script to push the metrics is being executed from crontab or via systemd. Running it manually doesn't shows this issue.

**Comment by mihaimyh** [comment]
More info, I was debugging what the `curl` command is sending to push gateway:
1. When the script is being run manually, everything looks ok:
```
2e00: rker/1:0]", pid="130216"} 0.0.memory_usage{process="[kworker/1:0
2e40: ]", pid="130216"} 0.0.cpu_usage{process="[kworker/2:1]", pid="13
2e80: 0251"} 0.0.memory_usage{process="[kworker/2:1]", pid="130251"} 0
2ec0: .0.cpu_usage{process="phantom", pid="130485"} 0.0.memory_usage{p
2f00: rocess="phantom", pid="130485"} 0.1.

```
 
2. Running it with systemd/cron it gets trimmed:
```
1780: _usage{process="[kworker/+", pid="130216"} 0.0.memory_usage{proc
17c0: ess="[kworker/+", pid="130216"} 0.0.cpu_usage{process="[kworker/
1800: +", pid="130251"} 0.0.memory_usage{process="[kworker/+", pid="13
1840: 0251"} 0.0.cpu_usage{process="phantom", pid="130485"} 0.0.memory
1880: _usage{process="phantom", pid="130485"} 0.1
```

**Comment by beorn7** [comment]
Weird. I can only imagine that some processing of the `${var}` content happens in some layer of variable expansion/escaping/quoting that you only have in cron or systemd and not directly on the command line.

I don't know those Unix and shell details enough to say for certain.

I usually use `--data-binary` rather than `--data`, when using `curl` to push, and I feed the data via STDIN (i.e. `curl --data-binary @-`). Not sure if you can try the same in your case.
