### ISSUE TITLE
Avoid an error level warning upon graceful shutdown

### ISSUE THREAD

**Issue by beorn7** [prometheus/pushgateway#427]
### Discussed in https://github.com/prometheus/pushgateway/discussions/426

<div type='discussions-op-text'>

<sup>Originally posted by **jiangpengjul** September 30, 2021</sup>

![image](https://user-images.githubusercontent.com/74517826/135400432-c56c6081-4caa-4b2c-a917-bc35a2619af8.png)

![image](https://user-images.githubusercontent.com/74517826/135400539-c9091e59-52f1-487f-a287-19650b48c53d.png)
</div>

**Comment by mjip** [comment]
Hi, do you mind if I give this one a shot? It looks like the ideal behaviour would be to only log an error-level message if this call returned an error, otherwise perhaps an info should be logged here-
https://github.com/prometheus/pushgateway/blob/079d8d899a0fc47c3b159df2b3a4ffc555170466/main.go#L198
Let me know if I'm way off-base

**Comment by beorn7** [comment]
See discussion on #428.
