### ISSUE TITLE
the same metric with different labels override each other

### ISSUE THREAD

**Issue by ShalomCohen** [prometheus/pushgateway#65]
So, If I try to send to the same push gateway the same metric but with different values in the labels they override each other using post(and put) - it seems that it replaces the metric no matter if replace is set to false or truth.

**Comment by beorn7** [comment]
That's by design.

If the grouping key and the name of the metric is the same, then metrics are always replaced, regardless if you use POST and PUT. POST will not replace metrics with a different _name_, though.

**Comment by radut** [comment]
"If the grouping key and the name of the metric is the same..."  What grouping key ?

Can I push same metric name different labels on one instance of pushgateway with different jobs,so that they don't override each other?

**Comment by sciffer** [comment]
You can as lonh as the grouping key is different.

**Comment by radut** [comment]
And what is the grouping key. What fields are in this grouping key?

**Comment by beorn7** [comment]
The README.md on https://github.com/prometheus/pushgateway explains the grouping key (just search for "grouping key" on that page to find all the occurrences).

In general, it makes more sense to ask questions like this on the [prometheus-users mailinglist](https://groups.google.com/forum/#!forum/prometheus-users") rather than in a GitHub issue.

**Comment by sreque** [comment]
This still feels like a bug or at least a design flaw to me. Say for instance, you have an ephemeral job like an AWS Lambda function processing files uploaded to an S3 bucket. There is no meaningful grouping key for this setup. It looks like, in order to get true "host"-less metrics, you have to stick a StatsD server in front of your push gateway to get useful metrics aggregation.

**Comment by brian-brazil** [comment]
Something statsd-like is one of the appropriate ways to deal with Lambda-like things. The pushgateway does not do temporal aggregation.

**Comment by alexklibisz** [comment]
For others looking, you can work around the last-write-wins semantic by using your labels as the grouping key. That took a while to figure out, and I'm not 100% sure if there's any consequence to doing it this way. In my case I'm using the Java client. I used the `push(CollectorRegistry registry, String job, Map<String, String> groupingKey)` method and passed my <String, String> map of labels as the groupingKey.

**Comment by wangxw666** [comment]
This is a bad design

**Comment by elsamhaa-g2-travel** [comment]
I'd hate to comment on an old issue, but I must say the current design is not good. The PUT/POST behaviors are counter-intuitive to say the least.

POST method should be associated with posting new/replacing.
PUT method should be associated with granular updating of the group (i.e metrics with the same name).

**Comment by ElSamhaa** [comment]
I'd hate to comment on an old issue, but I must say the current design is not good. The PUT/POST behaviors are counter-intuitive to say the least.

POST method should be associated with posting new/replacing.
PUT method should be associated with granular updating of the group (i.e metrics with the same name).

**Comment by mdebord-dlr** [comment]
>If the grouping key and the name of the metric is the same, then metrics are always replaced

Even with unique labels? Does anyone know where this is documented, I haven't seen it mentioned and I'm facing this same issue. 

The fact that unique labels don't actually make it unique is very counter intuitive.

**Comment by contrudar** [comment]
does anybody know how to work it around? For instance, how to use approach of @alexklibisz but using plain POST request

**Comment by sciffer** [comment]
I know it's an old thred that I opened up long time a go, but just in case someone need counter&histogram support for push gateway - you can try using the aggregation push gateway: https://github.com/zapier/prom-aggregation-gateway
While they solved the counter and histogram support, they broke the logic for gauges as those are treated as if they were counters (not sure why).

**Comment by bpoole6** [comment]
The gauge issue and having to restart prom-aggregation-gateway to delete stale metrics was a no go for our use case. That's why I created the **Metrics Accumulator** https://github.com/bpoole6/metrics-accumulator

The Metrics Accumulator  doesn't add gauge values together, it instead takes the latest value pushed for a gauge ([There is some customization here](https://github.com/bpoole6/metrics-accumulator/tree/main#gauges)).

It also has a **TTL** for your metrics.
