### ISSUE TITLE
Feature request: Gzip support

### ISSUE THREAD

**Issue by y8** [prometheus/pushgateway#84]
Hi.

Right now pushgateway can't accept requests with `Content-Encoding: gzip`. 

It would be nice if `pushgateway` could to accept gzipped pushes, to reduce traffic.

**Comment by brian-brazil** [comment]
If you've a use case where this matters, you may wish to reevaluate your use of the pushgateway.

See https://prometheus.io/docs/practices/pushing/

**Comment by beorn7** [comment]
If somebody has a need for this even after having read and understood https://prometheus.io/docs/practices/pushing/ , I'd be willing to accept a PR. However, it is unlikely that a Prometheus core developer will take this on as none of us has the use case where it matters.

**Comment by tompluess** [comment]
We have the same requirement here.
**Use case**: Several small devices should report their metrics to prometheus. these few devices are in heterogeneous networks, possible behind firewalls and may communicate to prometheus only through `https` as clients. Pushgateway seems to be the perfect solution for us. 
`Content-Encoding: gzip` would lower our network traffic drastically.

**Comment by brian-brazil** [comment]
@tompluess  This is not an appropriate use of the pushgateway. You want something like pushprox.

**Comment by beorn7** [comment]
Link to pushprox: https://github.com/RobustPerception/PushProx

**Comment by mohnishkodnani** [comment]
If you have a batch job, where the collector Registry is in 100's of MB in the text format, would that be a usecase where we could consider gzip encoding.

**Comment by beorn7** [comment]
The usual wisdom is that, if you really need to push 100s of MiB of metrics to the Pushgateway, you are not using it for its intended purpose.

But note that a PR that adds gzip support would be welcome, as said above. It's a feature that is of potential use for many use cases, including the intended ones, if network bandwidth is a scarce resource. I'm not going to block such a feature simply because it _also_ helps unintended use cases.

A more general note, however: In modern local networks, the CPU cycles to compress data are usually more expensive than the network bandwidth. https://github.com/kubernetes/kube-state-metrics, as an example, decided to disable gzip compression by default. It's not using the PGW, but it's offering humongous amounts of metrics for scraping. If the scrapes stays in the local network, it is both faster and less expensive if you disable compression.

**Comment by belm0** [comment]
I'm finding that pushgateway performs poorly anyway when serving `/metrics` with large number of metrics.  (So for this issue, even if some bandwidth issue is addressed with gzip, you may then hit a scrape time bottleneck.)

For example, GET of `/metrics` from localhost takes ~5s for a file with 400k metrics.
