### ISSUE TITLE
Inconsistent metric type is not validated on metric push and value ignored during scrape

### ISSUE THREAD

**Issue by iggyzap** [prometheus/pushgateway#99]
Hi,

I've observed following behavior with 0.3.1 version of push gateway - if pushing metric to gw and metric type changes then GW allows HTTP call with inconsistent type to complete but newer value does not propagate to prometheus server with error message dumped to log:
```
2016-12-14_18:29:19.58876 time="2016-12-14T18:29:19Z" level=warning msg="Metric families 'name:\"emr_job_execution_duration_s\" type:UNTYPED metric:<label:<name:\"instance\" value:\"local\" > label:<name:\"job\" value:\"emr_batch\" > label:<name:\"script\" value:\"foo\" > label:<name:\"status\" value:\"0\" > untyped:<value:1000 > timestamp_ms:1481739244000 > ' and 'name:\"emr_job_execution_duration_s\" type:GAUGE metric:<label:<name:\"instance\" value:\"\" > label:<name:\"job\" value:\"emr\" > label:<name:\"script\" value:\"blah\" > gauge:<value:500 > timestamp_ms:1481740382000 > metric:<label:<name:\"instance\" value:\"localhost.localdomain\" > label:<name:\"job\" value:\"emr\" > label:<name:\"script\" value:\"blah\" > gauge:<value:200 > timestamp_ms:1481740310000 > ' are inconsistent, help and type of the latter will have priority. This is bad. Fix your pushed metrics!" source="diskmetricstore.go:114"
```

Surprisingly, this contradicts to how prometheus server behaves - it allows metric type change !

Also this leaves people scratching their heads - why my metric did not appear in prometheus ?

Hope you'll be able to look into resolving the issue.

With regards, Ignat Zapolsky

**Comment by beorn7** [comment]
Pushgateway allows the metric type change, too. It just warns about it, in case it's something unintended.

As spelled out in the log message, the intended behavior is that the latest push wins, which is consistent with how the Prometheus server handles it.

How often does the warning show up? Perhaps you are still pushing both versions, so that the newer one gets "downgraded"?

In different news: You are pushing with a timestamp. That's a rather special use case (which isn't even supported in client libraries, exactly because it is so new). What timezone is your server in? In any case, it looks like your most recent pushed timestamp is in the future (which will make it not show up for the default timestamp of a query, which is "now").

To rule out timestamp problems, how about you stop pushing with a timestamp and see if the behavior matches expectations then?

**Comment by iggyzap** [comment]
Hi,

Thanks for your quick response!

I've changed script to not use date in the future and that resolved my issue.

So it's invalid user, and warning is good :)

**Comment by harighub** [comment]
I'm seeing similar issue at prometheus-pushgateway while pushing telegraf metrics. Wondering how it possible to remove stamp stamp at telegraf? I appreciate if you some suggestions.

time=“2017-08-04T19:40:25Z” level=warning msg=“Metric families ‘name:\“net_ip_fragoks\” type:UNTYPED metric:<label:<name:\“exported_instance\” value:\“host-level-ds-5z5qt\” > label:<name:\“exported_job\” value:\“target_9126\” > label:<name:\“host\” value:\“host-level-ds-5z5qt\” > label:<name:\“instance\” value:\“monitoring-190200609-rfjq8\” > label:<name:\“interface\” value:\“all\” > label:<name:\“job\” value:\“target_9090\” > label:<name:\“monitor\” value:\“codelab-monitor\” > untyped:<value:0 > timestamp_ms:1501875606715 > ’ and ‘name:\“net_ip_fragoks\” help:\“Telegraf collected metric\” type:UNTYPED metric:<label:<name:\“host\” value:\“host-level-ds-5z5qt\” > label:<name:\“instance\” value:\“host-level-ds-5z5qt\” > label:<name:\“interface\” value:\“all\” > label:<name:\“job\” value:\“target_9126\” > untyped:<value:0 > timestamp_ms:1501875616773 > metric:<label:<name:\“host\” value:\“host-level-ds-nxhph\” > label:<name:\“instance\” value:\“host-level-ds-nxhph\” > label:<name:\“interface\” value:\“all\” > label:<name:\“job\” value:\“target_9126\” > untyped:<value:0 > timestamp_ms:1501875616749 > ’ are inconsistent, help and type of the latter will have priority. This is bad. Fix your pushed metrics!” source=“diskmetricstore.go:114”

**Comment by beorn7** [comment]
@harighub It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue (which is even already closed in this case). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by baiwfg2** [comment]
I met the same issue. When I send a metrics, maybe not a valid format, it shows 

> Metric families 'name:"some_metric" type:COUNTER metric:<label:<name:"instance" value:"some_instance" > label:<name:"job" value:"some_job" > label:<name:"label" value:"val1" > counter:<value:42 > > ' and 'name:"some_metric" type:UNTYPED metric:<label:<name:"instance" value:"" > label:<name:"job" value:"some_job" > untyped:<value:3.14 > > ' are inconsistent, help and type of the latter will have priority. This is bad. Fix your pushed metrics!  source=diskmetricstore.go:114

Then I go to the prom dashboard and check the target status, it shows:
> Down. 
>Error is server returned HTTP status 500 Internal Server Error

So the log asks me to fix my pushed metrics. How to fix that ? After fixing,  will it automatically go back to normal without restarting ?
